feat: try to use podman instead of docker
Looks like this is not possible yet.
The run ends in:

Some option to use:

```
--sandbox_writable_path=/
```

end result:

```
cannot clone: Operation not permitted
Error: cannot re-exec process
```

For details see: https://github.com/filmil/bazel-rules-bid/issues/3